# Generated by Django 5.0 on 2023-12-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='本のタイトル')),
                ('writer', models.CharField(max_length=30, verbose_name='筆者')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('date', models.DateField(verbose_name='読了日')),
            ],
        ),
    ]
