# Generated by Django 5.0 on 2023-12-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='memo',
            field=models.TextField(blank=True, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='title',
            field=models.CharField(max_length=30, verbose_name='タイトル'),
        ),
    ]
