# Generated by Django 5.0 on 2023-12-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_alter_reading_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='memo',
            new_name='detail',
        ),
    ]
